pro: add libusb-1.0 to non-static link for Linux
Fixes failing link on Arch Linux with libmonero-wallet
4e723843183b12308bce2ef560385ea885ad0174

/usr/bin/ld:
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../lib/libwallet_merged.a(transport.cpp.o):
undefined reference to symbol 'libusb_interrupt_transfer'
/usr/bin/ld: /usr/lib/libusb-1.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status